import { EIL_ACTION_CATALOG, type EilActionDef } from "./catalog.js";

export type EilCategoryId =
  | "hospitality"
  | "ecommerce"
  | "customer_service"
  | "healthcare"
  | "real_estate"
  | "education"
  | "financial"
  | "billing_payments"
  | "restaurants_delivery"
  | "professional_services"
  | "saas"
  | "hr"
  | "sales"
  | "logistics"
  | "automotive"
  | "travel"
  | "condominiums"
  | "insurance"
  | "legal"
  | "custom";

export type EilCategoryDef = {
  id: EilCategoryId;
  labelPt: string;
  labelEn: string;
  descriptionPt: string;
  descriptionEn: string;
  icon: string;
  actions: EilActionDef[];
  suggestedFacts: string[];
};

const A = (id: string, labelPt: string, labelEn: string): EilActionDef => ({
  id,
  labelPt,
  labelEn,
  descriptionPt: labelPt,
  descriptionEn: labelEn,
});

/** Reutiliza IDs existentes no runtime quando o conceito coincide. */
const escalate = EIL_ACTION_CATALOG.find((a) => a.id === "escalate_human")!;
const complete = EIL_ACTION_CATALOG.find((a) => a.id === "complete_flow")!;
const askDoc = EIL_ACTION_CATALOG.find((a) => a.id === "ask_document")!;
const askPay = EIL_ACTION_CATALOG.find((a) => a.id === "ask_payment")!;
const assertOps = EIL_ACTION_CATALOG.find((a) => a.id === "assert_operational_data")!;
const confirm = EIL_ACTION_CATALOG.find((a) => a.id === "confirm")!;

export const EIL_CATEGORIES: EilCategoryDef[] = [
  {
    id: "hospitality",
    labelPt: "Hotelaria e Hospedagem",
    labelEn: "Hospitality",
    descriptionPt: "Reservas, hóspedes, documentos, pagamentos e atendimento operacional.",
    descriptionEn: "Reservations, guests, documents, payments, and operational service.",
    icon: "Hotel",
    actions: [...EIL_ACTION_CATALOG],
    suggestedFacts: [
      "reservationId",
      "reservationStatus",
      "guestsQuantity",
      "checkinStatus",
      "documentNumber",
      "paymentStatus",
      "guestName",
    ],
  },
  {
    id: "ecommerce",
    labelPt: "E-commerce",
    labelEn: "E-commerce",
    descriptionPt: "Pedidos, entregas, estoque, pagamentos e pós-venda.",
    descriptionEn: "Orders, shipping, inventory, payments, and post-sale.",
    icon: "ShoppingCart",
    actions: [
      A("consult_order", "Consultar pedido", "Look up order"),
      A("create_order", "Criar pedido", "Create order"),
      A("update_order", "Alterar pedido", "Update order"),
      A("cancel_order", "Cancelar pedido", "Cancel order"),
      A("consult_order_status", "Consultar status do pedido", "Check order status"),
      A("consult_stock", "Consultar estoque", "Check inventory"),
      A("consult_delivery", "Consultar entrega", "Track delivery"),
      A("inform_delivery_eta", "Informar prazo de entrega", "Share delivery ETA"),
      A("request_address", "Solicitar endereço", "Request address"),
      askDoc,
      askPay,
      A("confirm_payment", "Confirmar pagamento", "Confirm payment"),
      A("request_exchange", "Solicitar troca", "Request exchange"),
      A("request_return", "Solicitar devolução", "Request return"),
      assertOps,
      escalate,
      complete,
    ],
    suggestedFacts: ["orderId", "orderStatus", "paymentStatus", "deliveryStatus", "customerId", "totalAmount"],
  },
  {
    id: "customer_service",
    labelPt: "Atendimento ao Cliente",
    labelEn: "Customer Service",
    descriptionPt: "Identificação, protocolos, consultas e encaminhamentos.",
    descriptionEn: "Identification, tickets, lookups, and routing.",
    icon: "Headphones",
    actions: [
      A("request_identification", "Solicitar identificação", "Request identification"),
      confirm,
      A("consult_customer", "Consultar cliente", "Look up customer"),
      A("create_case", "Criar atendimento", "Create case"),
      A("consult_case", "Consultar atendimento", "Look up case"),
      A("create_protocol", "Criar protocolo", "Create protocol"),
      A("consult_protocol", "Consultar protocolo", "Look up protocol"),
      A("request_additional_info", "Solicitar informações adicionais", "Request additional information"),
      assertOps,
      A("transfer_department", "Transferir setor", "Transfer department"),
      escalate,
      complete,
    ],
    suggestedFacts: ["customerId", "caseId", "protocolId", "name", "email", "phone"],
  },
  {
    id: "healthcare",
    labelPt: "Saúde e Clínicas",
    labelEn: "Healthcare & Clinics",
    descriptionPt: "Agendamentos e fluxos administrativos (sem decisões clínicas).",
    descriptionEn: "Scheduling and admin flows (no clinical decisions).",
    icon: "HeartPulse",
    actions: [
      A("consult_appointment", "Consultar agendamento", "Look up appointment"),
      A("create_appointment", "Criar agendamento", "Create appointment"),
      A("update_appointment", "Alterar agendamento", "Reschedule appointment"),
      A("cancel_appointment", "Cancelar agendamento", "Cancel appointment"),
      A("request_patient_data", "Solicitar dados do paciente", "Request patient data"),
      confirm,
      A("confirm_attendance", "Confirmar presença", "Confirm attendance"),
      askDoc,
      A("inform_schedule", "Informar horário", "Share schedule"),
      assertOps,
      escalate,
      complete,
    ],
    suggestedFacts: ["appointmentId", "patientId", "appointmentStatus", "documentNumber", "name"],
  },
  {
    id: "real_estate",
    labelPt: "Imobiliário",
    labelEn: "Real Estate",
    descriptionPt: "Imóveis, visitas, propostas e documentação.",
    descriptionEn: "Properties, visits, proposals, and documents.",
    icon: "Building2",
    actions: [
      A("consult_property", "Consultar imóvel", "Look up property"),
      A("consult_availability", "Consultar disponibilidade", "Check availability"),
      A("register_interest", "Registrar interesse", "Register interest"),
      A("request_prospect_data", "Solicitar dados do interessado", "Request prospect data"),
      A("schedule_visit", "Agendar visita", "Schedule visit"),
      A("update_visit", "Alterar visita", "Reschedule visit"),
      A("cancel_visit", "Cancelar visita", "Cancel visit"),
      askDoc,
      A("send_proposal", "Enviar proposta", "Send proposal"),
      A("consult_proposal", "Consultar proposta", "Look up proposal"),
      assertOps,
      A("forward_broker", "Encaminhar para corretor", "Forward to broker"),
      complete,
    ],
    suggestedFacts: ["propertyId", "visitId", "proposalId", "name", "email", "phone"],
  },
  {
    id: "education",
    labelPt: "Educação",
    labelEn: "Education",
    descriptionPt: "Cursos, matrículas, pagamentos e materiais.",
    descriptionEn: "Courses, enrollment, payments, and materials.",
    icon: "GraduationCap",
    actions: [
      A("consult_course", "Consultar curso", "Look up course"),
      A("consult_class", "Consultar turma", "Look up class"),
      A("consult_enrollment", "Consultar matrícula", "Look up enrollment"),
      A("create_enrollment", "Criar matrícula", "Create enrollment"),
      A("request_student_data", "Solicitar dados do aluno", "Request student data"),
      askDoc,
      A("consult_payment", "Consultar pagamento", "Check payment"),
      A("inform_schedule", "Informar horário", "Share schedule"),
      A("send_material", "Enviar material", "Send material"),
      A("register_interest", "Registrar interesse", "Register interest"),
      assertOps,
      escalate,
      complete,
    ],
    suggestedFacts: ["courseId", "enrollmentId", "studentId", "paymentStatus", "name", "email"],
  },
  {
    id: "financial",
    labelPt: "Financeiro",
    labelEn: "Financial",
    descriptionPt: "Contas, transações, saldos e confirmações.",
    descriptionEn: "Accounts, transactions, balances, and confirmations.",
    icon: "Landmark",
    actions: [
      A("consult_account", "Consultar conta", "Look up account"),
      A("consult_transaction", "Consultar transação", "Look up transaction"),
      A("consult_status", "Consultar status", "Check status"),
      A("request_identification", "Solicitar identificação", "Request identification"),
      confirm,
      A("inform_balance", "Informar saldo", "Share balance"),
      A("request_confirmation", "Solicitar confirmação", "Request confirmation"),
      A("consult_billing", "Consultar cobrança", "Look up billing"),
      assertOps,
      escalate,
      complete,
    ],
    suggestedFacts: ["accountId", "transactionId", "balance", "paymentStatus", "customerId"],
  },
  {
    id: "billing_payments",
    labelPt: "Cobrança e Pagamentos",
    labelEn: "Billing & Payments",
    descriptionPt: "Cobranças, links de pagamento e negociação.",
    descriptionEn: "Billing, payment links, and negotiation.",
    icon: "CreditCard",
    actions: [
      A("consult_billing", "Consultar cobrança", "Look up billing"),
      A("create_billing", "Criar cobrança", "Create billing"),
      A("send_billing", "Enviar cobrança", "Send billing"),
      A("generate_payment_link", "Gerar link de pagamento", "Generate payment link"),
      A("consult_payment", "Consultar pagamento", "Check payment"),
      A("confirm_payment", "Confirmar pagamento", "Confirm payment"),
      A("inform_pending_amount", "Informar valor pendente", "Inform pending amount"),
      A("send_second_copy", "Enviar segunda via", "Send second copy"),
      A("negotiate_due_date", "Negociar vencimento", "Negotiate due date"),
      assertOps,
      escalate,
      complete,
    ],
    suggestedFacts: ["billingId", "paymentStatus", "totalAmount", "dueDate", "customerId"],
  },
  {
    id: "restaurants_delivery",
    labelPt: "Restaurantes e Delivery",
    labelEn: "Restaurants & Delivery",
    descriptionPt: "Cardápio, pedidos, entrega e pagamento.",
    descriptionEn: "Menu, orders, delivery, and payment.",
    icon: "UtensilsCrossed",
    actions: [
      A("consult_menu", "Consultar cardápio", "Browse menu"),
      A("consult_product", "Consultar produto", "Look up product"),
      A("create_order", "Criar pedido", "Create order"),
      A("update_order", "Alterar pedido", "Update order"),
      A("cancel_order", "Cancelar pedido", "Cancel order"),
      A("consult_order_status", "Consultar status do pedido", "Check order status"),
      A("request_address", "Solicitar endereço", "Request address"),
      A("request_payment_method", "Solicitar forma de pagamento", "Request payment method"),
      A("confirm_order", "Confirmar pedido", "Confirm order"),
      A("inform_eta", "Informar prazo", "Share ETA"),
      assertOps,
      escalate,
      complete,
    ],
    suggestedFacts: ["orderId", "orderStatus", "deliveryStatus", "totalAmount", "paymentStatus"],
  },
  {
    id: "professional_services",
    labelPt: "Serviços Profissionais",
    labelEn: "Professional Services",
    descriptionPt: "Solicitações, orçamentos e agendamentos.",
    descriptionEn: "Requests, quotes, and scheduling.",
    icon: "Briefcase",
    actions: [
      A("consult_service", "Consultar serviço", "Look up service"),
      A("request_client_data", "Solicitar dados do cliente", "Request client data"),
      A("create_request", "Criar solicitação", "Create request"),
      A("consult_request", "Consultar solicitação", "Look up request"),
      A("schedule_service", "Agendar atendimento", "Schedule service"),
      A("update_appointment", "Alterar agendamento", "Reschedule"),
      A("cancel_appointment", "Cancelar agendamento", "Cancel appointment"),
      A("send_quote", "Enviar orçamento", "Send quote"),
      A("confirm_quote", "Confirmar orçamento", "Confirm quote"),
      assertOps,
      escalate,
      complete,
    ],
    suggestedFacts: ["requestId", "quoteId", "appointmentId", "customerId", "name"],
  },
  {
    id: "saas",
    labelPt: "SaaS / Tecnologia",
    labelEn: "SaaS / Technology",
    descriptionPt: "Contas, assinaturas, tickets e suporte técnico.",
    descriptionEn: "Accounts, subscriptions, tickets, and support.",
    icon: "Cloud",
    actions: [
      A("consult_account", "Consultar conta", "Look up account"),
      A("consult_subscription", "Consultar assinatura", "Look up subscription"),
      A("update_subscription", "Alterar assinatura", "Update subscription"),
      A("cancel_subscription", "Cancelar assinatura", "Cancel subscription"),
      A("create_ticket", "Criar ticket", "Create ticket"),
      A("consult_ticket", "Consultar ticket", "Look up ticket"),
      A("request_technical_info", "Solicitar informações técnicas", "Request technical info"),
      A("request_confirmation", "Solicitar confirmação", "Request confirmation"),
      askPay,
      assertOps,
      A("escalate_support", "Escalar suporte", "Escalate support"),
      complete,
    ],
    suggestedFacts: ["accountId", "subscriptionId", "subscriptionStatus", "ticketId", "ticketStatus"],
  },
  {
    id: "hr",
    labelPt: "Recursos Humanos",
    labelEn: "Human Resources",
    descriptionPt: "Candidatos, entrevistas e processos seletivos.",
    descriptionEn: "Candidates, interviews, and hiring processes.",
    icon: "Users",
    actions: [
      A("consult_candidate", "Consultar candidato", "Look up candidate"),
      A("register_candidate", "Registrar candidato", "Register candidate"),
      A("request_candidate_data", "Solicitar dados do candidato", "Request candidate data"),
      A("schedule_interview", "Agendar entrevista", "Schedule interview"),
      A("update_interview", "Alterar entrevista", "Reschedule interview"),
      A("cancel_interview", "Cancelar entrevista", "Cancel interview"),
      askDoc,
      A("inform_process_status", "Informar status do processo", "Share process status"),
      assertOps,
      A("forward_recruiter", "Encaminhar para recrutador", "Forward to recruiter"),
      complete,
    ],
    suggestedFacts: ["candidateId", "interviewId", "processStatus", "name", "email"],
  },
  {
    id: "sales",
    labelPt: "Vendas / Comercial",
    labelEn: "Sales",
    descriptionPt: "Leads, propostas, reuniões e qualificação.",
    descriptionEn: "Leads, proposals, meetings, and qualification.",
    icon: "TrendingUp",
    actions: [
      A("identify_lead", "Identificar lead", "Identify lead"),
      A("register_lead", "Registrar lead", "Register lead"),
      A("qualify_lead", "Qualificar lead", "Qualify lead"),
      A("request_information", "Solicitar informações", "Request information"),
      A("consult_product", "Consultar produto", "Look up product"),
      A("send_proposal", "Enviar proposta", "Send proposal"),
      A("consult_proposal", "Consultar proposta", "Look up proposal"),
      A("schedule_meeting", "Agendar reunião", "Schedule meeting"),
      A("register_interest", "Registrar interesse", "Register interest"),
      assertOps,
      A("forward_sales_rep", "Encaminhar para vendedor", "Forward to sales rep"),
      complete,
    ],
    suggestedFacts: ["leadId", "proposalId", "productId", "name", "email", "phone"],
  },
  {
    id: "logistics",
    labelPt: "Logística e Entregas",
    labelEn: "Logistics & Delivery",
    descriptionPt: "Rastreamento, entregas e ocorrências.",
    descriptionEn: "Tracking, deliveries, and incidents.",
    icon: "Truck",
    actions: [
      A("consult_delivery", "Consultar entrega", "Track delivery"),
      A("consult_tracking", "Consultar rastreamento", "Track shipment"),
      A("update_address", "Alterar endereço", "Update address"),
      A("inform_eta", "Informar previsão", "Share ETA"),
      A("confirm_delivery", "Confirmar entrega", "Confirm delivery"),
      A("register_incident", "Registrar ocorrência", "Register incident"),
      A("consult_incident", "Consultar ocorrência", "Look up incident"),
      A("request_proof", "Solicitar comprovante", "Request proof"),
      assertOps,
      escalate,
      complete,
    ],
    suggestedFacts: ["deliveryId", "trackingCode", "deliveryStatus", "incidentId"],
  },
  {
    id: "automotive",
    labelPt: "Automotivo",
    labelEn: "Automotive",
    descriptionPt: "Veículos, serviços, orçamentos e agendamentos.",
    descriptionEn: "Vehicles, service, quotes, and scheduling.",
    icon: "Car",
    actions: [
      A("consult_vehicle", "Consultar veículo", "Look up vehicle"),
      A("request_vehicle_data", "Solicitar dados do veículo", "Request vehicle data"),
      A("request_plate", "Solicitar placa", "Request license plate"),
      A("schedule_service", "Agendar serviço", "Schedule service"),
      A("update_appointment", "Alterar agendamento", "Reschedule"),
      A("cancel_appointment", "Cancelar agendamento", "Cancel appointment"),
      A("send_quote", "Enviar orçamento", "Send quote"),
      A("consult_quote", "Consultar orçamento", "Look up quote"),
      A("inform_service_status", "Informar status do serviço", "Share service status"),
      assertOps,
      escalate,
      complete,
    ],
    suggestedFacts: ["vehicleId", "plate", "serviceId", "quoteId", "appointmentId"],
  },
  {
    id: "travel",
    labelPt: "Turismo e Viagens",
    labelEn: "Travel & Tourism",
    descriptionPt: "Reservas, itinerários e documentos de viagem.",
    descriptionEn: "Bookings, itineraries, and travel documents.",
    icon: "Plane",
    actions: [
      A("consult_booking", "Consultar reserva", "Look up booking"),
      A("create_booking", "Criar reserva", "Create booking"),
      A("update_booking", "Alterar reserva", "Update booking"),
      A("cancel_booking", "Cancelar reserva", "Cancel booking"),
      A("consult_availability", "Consultar disponibilidade", "Check availability"),
      A("request_traveler_data", "Solicitar dados do viajante", "Request traveler data"),
      askDoc,
      A("inform_itinerary", "Informar itinerário", "Share itinerary"),
      askPay,
      assertOps,
      escalate,
      complete,
    ],
    suggestedFacts: ["bookingId", "bookingStatus", "travelerId", "paymentStatus", "documentNumber"],
  },
  {
    id: "condominiums",
    labelPt: "Condomínios / Administração Predial",
    labelEn: "Condominiums",
    descriptionPt: "Moradores, visitantes, reservas e ocorrências.",
    descriptionEn: "Residents, visitors, bookings, and incidents.",
    icon: "Building",
    actions: [
      A("consult_resident", "Consultar morador", "Look up resident"),
      A("consult_unit", "Consultar unidade", "Look up unit"),
      A("register_visitor", "Registrar visitante", "Register visitor"),
      A("authorize_visitor", "Autorizar visitante", "Authorize visitor"),
      A("register_incident", "Registrar ocorrência", "Register incident"),
      A("consult_incident", "Consultar ocorrência", "Look up incident"),
      A("book_common_area", "Reservar área comum", "Book common area"),
      A("cancel_booking", "Cancelar reserva", "Cancel booking"),
      askDoc,
      assertOps,
      escalate,
      complete,
    ],
    suggestedFacts: ["unitId", "residentId", "visitorId", "incidentId", "bookingId"],
  },
  {
    id: "insurance",
    labelPt: "Seguros",
    labelEn: "Insurance",
    descriptionPt: "Apólices, sinistros e solicitações.",
    descriptionEn: "Policies, claims, and requests.",
    icon: "Shield",
    actions: [
      A("consult_policy", "Consultar apólice", "Look up policy"),
      A("consult_insured", "Consultar segurado", "Look up insured"),
      A("register_request", "Registrar solicitação", "Register request"),
      A("consult_request", "Consultar solicitação", "Look up request"),
      askDoc,
      A("register_claim", "Registrar sinistro", "Register claim"),
      A("consult_claim", "Consultar sinistro", "Look up claim"),
      assertOps,
      A("forward_agent", "Encaminhar para atendente", "Forward to agent"),
      complete,
    ],
    suggestedFacts: ["policyId", "claimId", "insuredId", "requestId", "documentNumber"],
  },
  {
    id: "legal",
    labelPt: "Jurídico",
    labelEn: "Legal",
    descriptionPt: "Atendimento administrativo e operacional (sem decisões jurídicas).",
    descriptionEn: "Admin and operational service (no legal decisions).",
    icon: "Scale",
    actions: [
      A("consult_client", "Consultar cliente", "Look up client"),
      A("consult_case", "Consultar processo", "Look up case"),
      askDoc,
      A("register_service", "Registrar atendimento", "Register service"),
      A("schedule_meeting", "Agendar reunião", "Schedule meeting"),
      A("consult_status", "Consultar status", "Check status"),
      A("send_document", "Enviar documento", "Send document"),
      assertOps,
      A("escalate_professional", "Escalar para profissional responsável", "Escalate to professional"),
      complete,
    ],
    suggestedFacts: ["clientId", "caseId", "documentNumber", "name", "email"],
  },
  {
    id: "custom",
    labelPt: "Personalizada",
    labelEn: "Custom",
    descriptionPt: "Catálogo de ações definido pela sua organização.",
    descriptionEn: "Action catalog defined by your organization.",
    icon: "Sparkles",
    actions: [],
    suggestedFacts: [],
  },
];
