import type { HelpArticle } from "../types";

export const automationArticles: HelpArticle[] = [
  {
    id: "automation-overview",
    slug: "automation/overview",
    title: "Automação e Inteligência",
    description: "Visão geral das abas: conhecimento, agentes, ferramentas, prompts e mais.",
    categoryId: "automation",
    keywords: ["automação", "ia", "agente", "inteligência"],
    level: "basic",
    readMinutes: 4,
    requiresAdmin: true,
    routeContext: ["/automation"],
    relatedSlugs: ["automation/knowledge-base", "automation/agent-profiles", "automation/tools"],
    blocks: [
      { type: "heading", id: "tabs", level: 2, text: "Abas disponíveis" },
      {
        type: "list",
        items: [
          "Visão geral — resumo e atalhos.",
          "Base de conhecimento — artigos para RAG.",
          "Agentes — perfis por bot (LLM, comportamento, prompts).",
          "Chatbots — fluxos conversacionais (se habilitado).",
          "Ferramentas — HTTP tools e integrações.",
          "Prompts — biblioteca de instruções.",
          "Interações — histórico de turnos do agente.",
          "Execuções — logs detalhados de execução.",
          "Contexto — memória e contexto de conversa.",
          "CRM Flows — automações de CRM (se habilitado).",
        ],
      },
      {
        type: "callout",
        variant: "info",
        text: "Organizações em modo piloto podem ver apenas Base de conhecimento e Ferramentas.",
      },
    ],
  },
  {
    id: "automation-knowledge",
    slug: "automation/knowledge-base",
    title: "Base de Conhecimento",
    description: "Forneça informações da empresa para os agentes utilizarem no atendimento.",
    categoryId: "automation",
    keywords: ["conhecimento", "rag", "artigo", "kb", "knowledge"],
    level: "basic",
    readMinutes: 5,
    requiresAdmin: true,
    relatedSlugs: ["automation/rag-logical", "automation/agent-profiles"],
    blocks: [
      { type: "heading", id: "what", level: 2, text: "O que é?" },
      {
        type: "paragraph",
        text: "A Base de Conhecimento permite cadastrar textos, URLs e documentos que o agente consulta antes de responder. Ideal para políticas, FAQs, cardápios e procedimentos internos.",
      },
      { type: "heading", id: "configure", level: 2, text: "Como configurar" },
      {
        type: "steps",
        steps: [
          { title: "Automação → Base de conhecimento", body: "Acesse a aba correspondente." },
          { title: "Adicione fontes", body: "Texto manual, URL ou upload conforme opções disponíveis." },
          { title: "Aguarde indexação", body: "Novos conteúdos podem levar alguns instantes para ficarem disponíveis." },
          { title: "Associe ao agente", body: "Confirme que o perfil do bot usa a base de conhecimento." },
        ],
      },
      { type: "heading", id: "advanced", level: 3, text: "Detalhes técnicos" },
      {
        type: "paragraph",
        text: "Internamente, trechos relevantes são recuperados por similaridade semântica (RAG) e injetados no contexto do modelo. Você não precisa configurar embeddings manualmente.",
      },
    ],
  },
  {
    id: "automation-rag",
    slug: "automation/rag-logical",
    title: "RAG lógico",
    description: "Quando usar conhecimento estruturado vs. busca geral.",
    categoryId: "automation",
    keywords: ["rag", "lógico", "logical rag", "fatores", "regras"],
    level: "advanced",
    readMinutes: 5,
    requiresAdmin: true,
    relatedSlugs: ["automation/knowledge-base", "automation/eil"],
    blocks: [
      { type: "heading", id: "what", level: 2, text: "O que é?" },
      {
        type: "paragraph",
        text: "RAG lógico complementa a base de conhecimento com regras e fatos estruturados — útil quando respostas devem seguir dados precisos (preços, disponibilidade, políticas) em vez de texto livre.",
      },
      { type: "heading", id: "when", level: 2, text: "Quando usar?" },
      {
        type: "list",
        items: [
          "Respostas devem citar valores ou regras exatas.",
          "Conteúdo muda frequentemente e precisa de validação.",
          "Integração com EIL para políticas e facts.",
        ],
      },
    ],
  },
  {
    id: "automation-agents",
    slug: "automation/agent-profiles",
    title: "Perfis de agente por Bot",
    description: "Relação bot-agente, LLM, comportamento e ferramentas.",
    categoryId: "automation",
    keywords: ["agente", "perfil", "llm", "bot", "comportamento"],
    level: "intermediate",
    readMinutes: 6,
    requiresAdmin: true,
    routeContext: ["/automation"],
    relatedSlugs: ["automation/prompts", "automation/tools", "bots/create"],
    blocks: [
      { type: "heading", id: "what", level: 2, text: "O que é um perfil?" },
      {
        type: "paragraph",
        text: "Cada bot pode ter um perfil de agente com modelo de linguagem, temperatura, módulos de prompt, ferramentas habilitadas e regras de comportamento.",
      },
      { type: "heading", id: "configure", level: 2, text: "Como configurar" },
      {
        type: "steps",
        steps: [
          { title: "Automação → Agentes", body: "Selecione o bot na lista." },
          { title: "Ajuste LLM", body: "Modelo, temperatura e limites de tokens." },
          { title: "Vincule prompts", body: "Escolha módulos da biblioteca de prompts." },
          { title: "Habilite ferramentas", body: "Tools nativas e HTTP customizadas." },
          { title: "Salve e teste", body: "Envie mensagem de teste pelo canal." },
        ],
      },
      {
        type: "callout",
        variant: "tip",
        text: "Crie perfis diferentes quando o mesmo bot atende vendas e suporte com instruções distintas.",
      },
    ],
  },
  {
    id: "automation-tools",
    slug: "automation/tools",
    title: "Ferramentas (Tools)",
    description: "HTTP tools, parâmetros, autenticação e testes.",
    categoryId: "automation",
    keywords: ["ferramenta", "tool", "http", "api", "integração"],
    level: "intermediate",
    readMinutes: 7,
    requiresAdmin: true,
    relatedSlugs: ["automation/agent-profiles", "automation/eil"],
    blocks: [
      { type: "heading", id: "what", level: 2, text: "O que são?" },
      {
        type: "paragraph",
        text: "Ferramentas permitem que o agente chame APIs externas — consultar estoque, criar pedido, agendar horário. Cada tool define método HTTP, URL, parâmetros e autenticação.",
      },
      { type: "heading", id: "create", level: 2, text: "Como criar" },
      {
        type: "steps",
        steps: [
          { title: "Automação → Ferramentas", body: "Clique em nova ferramenta HTTP." },
          { title: "Defina nome e descrição", body: "O modelo usa a descrição para decidir quando invocar." },
          { title: "Configure endpoint", body: "URL, método, headers e body template." },
          { title: "Parâmetros", body: "Campos que o agente preenche dinamicamente." },
          { title: "Teste", body: "Use o sandbox de teste antes de associar ao agente." },
        ],
      },
      {
        type: "callout",
        variant: "important",
        text: "Erros comuns: URL incorreta, autenticação expirada ou descrição vaga que faz o agente não usar a tool.",
      },
    ],
  },
  {
    id: "automation-prompts",
    slug: "automation/prompts",
    title: "Prompts",
    description: "Instruções do agente, boas práticas e relação com ferramentas.",
    categoryId: "automation",
    keywords: ["prompt", "instrução", "system", "módulo"],
    level: "intermediate",
    readMinutes: 5,
    requiresAdmin: true,
    relatedSlugs: ["automation/agent-profiles"],
    blocks: [
      { type: "heading", id: "what", level: 2, text: "O que é um prompt?" },
      {
        type: "paragraph",
        text: "Prompts são blocos de instrução que definem tom, limites e procedimentos do agente. Podem ser reutilizados em vários perfis.",
      },
      { type: "heading", id: "best", level: 2, text: "Boas práticas" },
      {
        type: "list",
        items: [
          "Seja específico sobre o que o agente pode e não pode fazer.",
          "Referencie ferramentas pelo nome quando deve usá-las.",
          "Inclua exemplos de resposta para casos frequentes.",
          "Teste alterações em conversa real antes de produção.",
        ],
      },
    ],
  },
  {
    id: "automation-interactions",
    slug: "automation/interactions",
    title: "Interações",
    description: "Histórico de turnos, filtros e interpretação.",
    categoryId: "automation",
    keywords: ["interação", "turno", "histórico", "log"],
    level: "intermediate",
    readMinutes: 4,
    requiresAdmin: true,
    relatedSlugs: ["automation/executions", "conversations/overview"],
    blocks: [
      { type: "heading", id: "what", level: 2, text: "O que representa?" },
      {
        type: "paragraph",
        text: "Interações registram cada turno do agente: mensagem recebida, raciocínio, tools invocadas e resposta gerada. Use para auditar qualidade e debug.",
      },
      { type: "heading", id: "when", level: 2, text: "Quando consultar?" },
      {
        type: "paragraph",
        text: "Quando um cliente reporta resposta incorreta ou quando você alterou prompts/ferramentas e quer validar o comportamento.",
      },
    ],
  },
  {
    id: "automation-context",
    slug: "automation/context",
    title: "Contexto de conversa",
    description: "Memória disponível, impacto no atendimento e configuração.",
    categoryId: "automation",
    keywords: ["contexto", "memória", "histórico", "conversation context"],
    level: "intermediate",
    readMinutes: 4,
    requiresAdmin: true,
    relatedSlugs: ["automation/agent-profiles"],
    blocks: [
      { type: "heading", id: "what", level: 2, text: "O que é?" },
      {
        type: "paragraph",
        text: "Contexto de conversa define quanto histórico e memória externa o agente recebe a cada turno. Mais contexto melhora continuidade, mas consome tokens e pode diluir instruções.",
      },
      {
        type: "callout",
        variant: "tip",
        text: "Para atendimentos longos, combine contexto moderado com base de conhecimento para fatos estáveis.",
      },
    ],
  },
  {
    id: "automation-reminders",
    slug: "automation/reminders",
    title: "Lembretes da organização",
    description: "Criação, disparo e relação com conversas.",
    categoryId: "automation",
    keywords: ["lembrete", "reminder", "tarefa", "follow-up"],
    level: "basic",
    readMinutes: 3,
    featureFlag: "reminders",
    relatedSlugs: ["conversations/overview"],
    blocks: [
      { type: "heading", id: "what", level: 2, text: "Finalidade" },
      {
        type: "paragraph",
        text: "Lembretes alertam atendentes sobre tarefas pendentes vinculadas a conversas ou contatos. Acesse pelo menu Lembretes ou banner contextual.",
      },
      { type: "heading", id: "create", level: 2, text: "Como criar" },
      {
        type: "paragraph",
        text: "Na conversa ou página de Lembretes, defina título, data/hora e responsável. Lembretes vencidos aparecem no banner de ações pendentes.",
      },
    ],
  },
  {
    id: "automation-eil",
    slug: "automation/eil",
    title: "Execution Intelligence Layer (EIL)",
    description: "Políticas, facts e validação de ações do agente.",
    categoryId: "automation",
    keywords: ["eil", "política", "facts", "requires", "forbids"],
    level: "advanced",
    readMinutes: 8,
    requiresAdmin: true,
    relatedSlugs: ["automation/tools", "automation/rag-logical"],
    blocks: [
      { type: "heading", id: "what", level: 2, text: "O que é?" },
      {
        type: "paragraph",
        text: "O EIL ajuda a garantir que o agente respeite regras e dados conhecidos antes de executar ou responder determinadas ações — por exemplo, não confirmar reserva sem disponibilidade verificada.",
      },
      { type: "heading", id: "concepts", level: 2, text: "Conceitos" },
      {
        type: "list",
        items: [
          "Políticas — regras por categoria de ação.",
          "Facts — fatos estruturados consultados em runtime.",
          "requires / forbids — condições para permitir ou bloquear tools.",
          "Templates — respostas quando uma política bloqueia a ação.",
        ],
      },
      {
        type: "callout",
        variant: "admin",
        text: "Configure EIL no perfil do agente e nas ferramentas associadas. Use Interações e Execuções para ver decisões do EIL.",
      },
    ],
  },
];
