import type { HelpArticle } from "../types";

export const campaignsArticles: HelpArticle[] = [
  {
    id: "campaigns-overview",
    slug: "campaigns/overview",
    title: "Centro de Campanhas Omnichannel",
    description: "Visão geral do módulo de campanhas, abas e canais disponíveis.",
    categoryId: "campaigns",
    keywords: ["campanha", "broadcast", "omnichannel", "envio em massa"],
    level: "basic",
    readMinutes: 4,
    requiresAdmin: true,
    featureFlag: "broadcast_campaigns",
    routeContext: ["/broadcasts"],
    relatedSlugs: ["campaigns/create", "campaigns/follow-up", "campaigns/templates"],
    blocks: [
      { type: "heading", id: "what", level: 2, text: "O que é?" },
      {
        type: "paragraph",
        text: "O Centro de Campanhas reúne ferramentas para comunicação, acompanhamento e automação de contatos em diferentes canais. Acesse pelo menu Campanhas (administradores).",
      },
      { type: "heading", id: "tabs", level: 2, text: "Abas do centro" },
      {
        type: "list",
        items: [
          "Campanhas — criar, agendar e acompanhar envios.",
          "Follow-up — campanhas de reengajamento por tags e condições.",
          "Lead Finder — prospecção (quando habilitado para a organização).",
          "Templates — biblioteca de modelos reutilizáveis.",
          "Fluxos — automações visuais de campanha.",
          "Analytics — métricas e desempenho.",
        ],
      },
      {
        type: "callout",
        variant: "info",
        text: "Lead Finder só aparece se a funcionalidade estiver habilitada pelo super administrador.",
      },
    ],
  },
  {
    id: "campaigns-what",
    slug: "campaigns/what-are-campaigns",
    title: "O que são Campanhas?",
    description: "Finalidade, público, canais, estados e métricas de campanhas.",
    categoryId: "campaigns",
    keywords: ["campanha", "envio", "público", "segmento", "status"],
    level: "basic",
    readMinutes: 5,
    requiresAdmin: true,
    featureFlag: "broadcast_campaigns",
    relatedSlugs: ["campaigns/create", "campaigns/analytics"],
    blocks: [
      { type: "heading", id: "purpose", level: 2, text: "Para que serve?" },
      {
        type: "paragraph",
        text: "Campanhas permitem enviar mensagens para grupos de contatos filtrados por tags, etapas do funil, tipos de lead ou regras avançadas. Use para avisos, promoções, reativação ou comunicados.",
      },
      { type: "heading", id: "channels", level: 2, text: "Canais" },
      {
        type: "paragraph",
        text: "Dependem das caixas de entrada configuradas (WhatsApp, SMS, etc.). Selecione o canal ao criar a campanha.",
      },
      { type: "heading", id: "states", level: 2, text: "Estados" },
      {
        type: "list",
        items: [
          "Rascunho — em elaboração, ainda não enviada.",
          "Agendada — programada para data/hora futura.",
          "Em execução — envios em andamento.",
          "Concluída — processamento finalizado.",
          "Cancelada — interrompida antes da conclusão.",
        ],
      },
      {
        type: "callout",
        variant: "tip",
        text: "Consulte Analytics para saber quando revisar taxa de entrega e respostas — idealmente 24–48h após envios grandes.",
      },
    ],
  },
  {
    id: "campaigns-create",
    slug: "campaigns/create",
    title: "Como criar uma campanha",
    description: "Fluxo real de criação: modo rápido, fluxo ou IA.",
    categoryId: "campaigns",
    keywords: ["criar campanha", "nova campanha", "enviar", "segmento"],
    level: "basic",
    readMinutes: 6,
    requiresAdmin: true,
    featureFlag: "broadcast_campaigns",
    routeContext: ["/broadcasts"],
    relatedSlugs: ["campaigns/templates", "campaigns/analytics"],
    blocks: [
      { type: "heading", id: "steps", level: 2, text: "Passo a passo" },
      {
        type: "steps",
        steps: [
          { title: "Abra Campanhas", body: "Menu lateral → Campanhas." },
          { title: "Clique em Nova campanha", body: "Abre o painel criador." },
          { title: "Escolha o modo", body: "Rápido, Fluxo ou IA — conforme complexidade desejada." },
          { title: "Defina nome e canal", body: "Selecione inbox/canal de envio." },
          { title: "Configure o público", body: "Tags, etapas, tipos de lead ou preview de segmento." },
          { title: "Escreva ou selecione template", body: "Mensagem com variáveis quando disponível." },
          { title: "Programe ou envie agora", body: "Agendamento opcional." },
          { title: "Revise e confirme", body: "Verifique contagem de destinatários antes de enviar." },
        ],
      },
      {
        type: "callout",
        variant: "important",
        text: "Respeite políticas do WhatsApp Business: use templates aprovados quando exigido pelo canal.",
      },
    ],
  },
  {
    id: "campaigns-follow-up",
    slug: "campaigns/follow-up",
    title: "O que é Follow-up?",
    description: "Automatize novos contatos após interações ou condições.",
    categoryId: "campaigns",
    keywords: ["follow-up", "followup", "reenvio", "automático", "tags"],
    level: "basic",
    readMinutes: 4,
    requiresAdmin: true,
    featureFlag: "broadcast_campaigns",
    relatedSlugs: ["campaigns/create", "campaigns/templates"],
    blocks: [
      { type: "heading", id: "what", level: 2, text: "O que é?" },
      {
        type: "paragraph",
        text: "Follow-ups permitem programar ou automatizar novos contatos depois de determinadas interações ou condições — por exemplo, contatos com certa tag que não responderam.",
      },
      { type: "heading", id: "configure", level: 2, text: "Como configurar" },
      {
        type: "steps",
        steps: [
          { title: "Aba Follow-up", body: "No Centro de Campanhas." },
          { title: "Defina regras de tag", body: "Inclusão/exclusão de tags conforme a interface." },
          { title: "Configure mensagem e canal", body: "Similar a campanhas normais." },
          { title: "Ative e monitore", body: "Acompanhe status na lista de campanhas." },
        ],
      },
    ],
  },
  {
    id: "campaigns-templates",
    slug: "campaigns/templates",
    title: "Templates de campanha",
    description: "Crie, edite e reutilize modelos de mensagem.",
    categoryId: "campaigns",
    keywords: ["template", "modelo", "mensagem", "variáveis", "whatsapp"],
    level: "basic",
    readMinutes: 4,
    requiresAdmin: true,
    featureFlag: "broadcast_campaigns",
    relatedSlugs: ["campaigns/create", "settings/templates"],
    blocks: [
      { type: "heading", id: "what", level: 2, text: "O que são?" },
      {
        type: "paragraph",
        text: "Templates são mensagens pré-formatadas usadas em campanhas e, em alguns canais, exigidas pelo provedor (ex.: templates WhatsApp aprovados).",
      },
      { type: "heading", id: "create", level: 2, text: "Como criar" },
      {
        type: "paragraph",
        text: "Na aba Templates do Centro de Campanhas ou em Configurações → Templates (templates de canal). Informe nome, corpo e variáveis suportadas pelo canal.",
      },
      {
        type: "callout",
        variant: "tip",
        text: "Mantenha templates curtos e com call-to-action claro para melhor taxa de resposta.",
      },
    ],
  },
  {
    id: "campaigns-flows",
    slug: "campaigns/flows",
    title: "Fluxos de campanha",
    description: "Automações visuais com gatilhos, condições e ações.",
    categoryId: "campaigns",
    keywords: ["fluxo", "flow", "automação", "gatilho", "ação"],
    level: "intermediate",
    readMinutes: 5,
    requiresAdmin: true,
    featureFlag: "broadcast_campaigns",
    relatedSlugs: ["campaigns/create", "automation/overview"],
    blocks: [
      { type: "heading", id: "what", level: 2, text: "O que são?" },
      {
        type: "paragraph",
        text: "Fluxos permitem encadear gatilhos (ex.: tag adicionada), condições e ações (enviar mensagem, aguardar, atualizar CRM) sem criar campanhas manuais repetidas.",
      },
      { type: "heading", id: "test", level: 2, text: "Como testar" },
      {
        type: "paragraph",
        text: "Crie o fluxo em modo rascunho, aplique a um contato de teste e verifique execução em Analytics e histórico da campanha.",
      },
    ],
  },
  {
    id: "campaigns-analytics",
    slug: "campaigns/analytics",
    title: "Analytics de campanhas",
    description: "Interpretar métricas, filtros e quando agir sobre os resultados.",
    categoryId: "campaigns",
    keywords: ["analytics", "métricas", "relatório", "taxa", "entrega"],
    level: "intermediate",
    readMinutes: 4,
    requiresAdmin: true,
    featureFlag: "broadcast_campaigns",
    relatedSlugs: ["campaigns/what-are-campaigns"],
    blocks: [
      { type: "heading", id: "purpose", level: 2, text: "Quando olhar?" },
      {
        type: "paragraph",
        text: "Use Analytics após envios para avaliar entrega, falhas e engajamento. Compare campanhas similares para refinar público e mensagem.",
      },
      { type: "heading", id: "metrics", level: 2, text: "Indicadores" },
      {
        type: "list",
        items: [
          "Enviados / entregues — saúde do canal e qualidade dos números.",
          "Falhas — investigue templates, opt-out ou números inválidos.",
          "Respostas — eficácia da copy e timing do envio.",
        ],
      },
    ],
  },
];
