import type { HelpArticle } from "../types";

export const settingsArticles: HelpArticle[] = [
  {
    id: "settings-overview",
    slug: "settings/overview",
    title: "Configurações da organização",
    description: "Mapa das abas disponíveis em Configurações.",
    categoryId: "settings",
    keywords: ["configurações", "settings", "organização", "admin"],
    level: "basic",
    readMinutes: 4,
    requiresAdmin: true,
    routeContext: ["/settings"],
    relatedSlugs: ["settings/channel", "settings/team"],
    blocks: [
      { type: "heading", id: "access", level: 2, text: "Como acessar" },
      {
        type: "paragraph",
        text: "Menu do perfil → Configurações. Somente administradores da organização.",
      },
      { type: "heading", id: "tabs", level: 2, text: "Abas principais" },
      {
        type: "list",
        items: [
          "Canal — WhatsApp (Evolution, Embedded, etc.) e provedores.",
          "Aparência — logo e tema do widget de conversa.",
          "Notificações — alertas de novas mensagens.",
          "CSAT — pesquisas de satisfação.",
          "SLA — políticas de tempo de resposta.",
          "Respostas prontas — canned responses.",
          "Workflow — auto-resolve e regras de encerramento.",
          "Assistente — chave OpenAI organizacional.",
          "CRM — tipos de lead e negócios.",
          "Templates — modelos WhatsApp.",
          "Tags — tags da organização.",
          "Equipe — membros e convites.",
          "Billing — plano e faturamento.",
          "Integrações de voz — Wavoip, 3CX, Nvoip (conforme flags).",
        ],
      },
    ],
  },
  {
    id: "settings-channel",
    slug: "settings/channel",
    title: "Configurar canais",
    description: "WhatsApp, webhooks de canal e caixas de entrada.",
    categoryId: "settings",
    keywords: ["canal", "whatsapp", "evolution", "webhook", "conexão"],
    level: "intermediate",
    readMinutes: 6,
    requiresAdmin: true,
    relatedSlugs: ["bots/create", "settings/inboxes"],
    blocks: [
      { type: "heading", id: "channel", level: 2, text: "Aba Canal" },
      {
        type: "paragraph",
        text: "Configure provedor WhatsApp, credenciais e URLs de webhook conforme instruções do provedor escolhido.",
      },
      {
        type: "callout",
        variant: "important",
        text: "Alterações de canal podem exigir reconexão QR ou validação Meta — planeje janela de manutenção.",
      },
    ],
  },
  {
    id: "settings-team",
    slug: "settings/team",
    title: "Usuários e equipe",
    description: "Convites, papéis e permissões básicas.",
    categoryId: "settings",
    keywords: ["usuário", "equipe", "convite", "admin", "agente", "permissão"],
    level: "basic",
    readMinutes: 4,
    requiresAdmin: true,
    relatedSlugs: ["settings/overview"],
    blocks: [
      { type: "heading", id: "roles", level: 2, text: "Papéis" },
      {
        type: "list",
        items: [
          "ADMIN — acesso total à organização.",
          "AGENT — atendimento e CRM conforme permissões.",
        ],
      },
      { type: "heading", id: "invite", level: 2, text: "Convidar" },
      {
        type: "steps",
        steps: [
          { title: "Configurações → Equipe", body: "Ou aba Team." },
          { title: "Novo convite", body: "Informe e-mail e papel." },
          { title: "Usuário aceita link", body: "Cadastro via /invite." },
        ],
      },
    ],
  },
  {
    id: "settings-crm",
    slug: "settings/crm",
    title: "Configurações CRM",
    description: "Tipos de lead, categorias de negócio e campos.",
    categoryId: "settings",
    keywords: ["crm settings", "tipo lead", "categoria negócio"],
    level: "intermediate",
    readMinutes: 4,
    requiresAdmin: true,
    featureFlag: "crm_kanban",
    relatedSlugs: ["crm/configure", "deals/categories"],
    blocks: [
      {
        type: "paragraph",
        text: "Na aba CRM de Configurações, ajuste tipos de lead, etapas e — se Negócios estiver habilitado — categorias e campos personalizados.",
      },
    ],
  },
  {
    id: "settings-templates",
    slug: "settings/templates",
    title: "Templates de mensagem",
    description: "Templates WhatsApp aprovados pela organização.",
    categoryId: "settings",
    keywords: ["template", "whatsapp", "hsm", "mensagem"],
    level: "intermediate",
    readMinutes: 4,
    requiresAdmin: true,
    relatedSlugs: ["campaigns/templates"],
    blocks: [
      {
        type: "paragraph",
        text: "Gerencie templates sincronizados com o provedor WhatsApp. Necessários para mensagens proativas fora da janela de 24h.",
      },
    ],
  },
  {
    id: "settings-inboxes",
    slug: "settings/inboxes",
    title: "Caixas de entrada",
    description: "Criar e gerenciar inboxes por canal ou equipe.",
    categoryId: "settings",
    keywords: ["inbox", "caixa de entrada", "email"],
    level: "basic",
    readMinutes: 4,
    requiresAdmin: true,
    routeContext: ["/inboxes"],
    relatedSlugs: ["conversations/overview"],
    blocks: [
      {
        type: "paragraph",
        text: "Em Caixas de entrada (menu admin), crie inboxes vinculadas a canais. Inboxes EMAIL abrem workspace de e-mail dedicado.",
      },
    ],
  },
];
