export const announcementCopy = {
  "pt-BR": {
    title: "Mural de Avisos",
    subtitle: "Acompanhe novidades, atualizações, melhorias e comunicados importantes do OpenNexo.",
    search: "Buscar no mural...",
    all: "Todos",
    unread: "Não lidas",
    emptyTitle: "Nenhuma novidade por enquanto.",
    emptyBody: "Quando houver atualizações, novidades ou comunicados importantes do OpenNexo, eles aparecerão aqui.",
    allRead: "Tudo em dia",
    allReadBody: "Você já conferiu todas as novidades.",
    markAll: "Marcar todas como lidas",
    open: "Ver publicação",
    new: "Novo",
    featured: "Destaque",
    pinned: "Fixado",
    back: "Voltar ao mural",
    acknowledge: "Entendi",
    acknowledged: "Leitura confirmada",
    loadError: "Não foi possível carregar o mural.",
    previous: "Anterior",
    next: "Próxima",
    byline: "OpenNexo",
    bellTitle: "Nova atualização do OpenNexo",
    bellOpen: "Abrir mural",
    adminNew: "Nova publicação",
    adminSearch: "Buscar...",
    draft: "Rascunho",
    scheduled: "Agendado",
    published: "Publicado",
    archived: "Arquivado",
    saveDraft: "Salvar rascunho",
    preview: "Visualizar",
    publish: "Publicar agora",
    schedule: "Agendar",
    content: "Conteúdo",
    summary: "Resumo",
    category: "Categoria",
    cover: "Capa",
    coverHint: "Opcional. PNG, JPEG, WebP ou GIF até 2 MB.",
    body: "Conteúdo",
    audience: "Público",
    allOrgs: "Todas as organizações",
    specificOrgs: "Organizações específicas",
    specificPlans: "Planos específicos",
    searchOrgs: "Buscar organização",
    priority: "Prioridade",
    normal: "Normal",
    important: "Importante",
    critical: "Crítica",
    notify: "Enviar para a central de notificações",
    feature: "Destacar",
    pin: "Fixar no topo",
    requireAck: "Exigir confirmação de leitura",
    when: "Quando publicar?",
    now: "Agora",
    later: "Agendar",
    date: "Data e hora",
    timezone: "Fuso",
    visibleUntil: "Visível até",
    ctaText: "Texto do botão",
    ctaUrl: "Destino",
    cancel: "Cancelar",
    publishConfirm: "Publicar aviso?",
    publishHint: "Esta publicação ficará disponível para",
    users: "usuários",
    organizations: "organizações",
    confirm: "Publicar",
    archive: "Arquivar",
    duplicate: "Duplicar",
    remove: "Excluir",
    removeConfirm: "Excluir esta publicação de forma definitiva do mural? O registro permanece arquivado no histórico administrativo.",
    renotify: "Notificar novamente",
    renotifyConfirm: "Isso marca a publicação como não lida para os usuários elegíveis e envia o aviso de novo. Continuar?",
    metrics: "Métricas",
    reachedOrgs: "Organizações alcançadas",
    eligibleUsers: "Usuários elegíveis",
    reads: "Usuários que leram",
    readRate: "Taxa de leitura",
    acks: "Confirmações",
    metricsHint: "Leitura conta quem abriu a publicação. Não medimos impressões do card.",
    status: "Status",
    audienceCol: "Público",
    unsaved: "Há alterações não salvas. Sair mesmo assim?",
    desktop: "Desktop",
    mobile: "Mobile",
    previewTitle: "Pré-visualização",
    noPlans: "Nenhum plano ativo encontrado.",
    saved: "Rascunho salvo.",
    publishedOk: "Publicação disponível.",
    scheduledOk: "Publicação agendada.",
    categoryName: "Nome da categoria",
    addCategory: "Nova categoria",
  },
  en: {
    title: "Announcements",
    subtitle: "Follow product news, updates, improvements, and important notices from OpenNexo.",
    search: "Search announcements...",
    all: "All",
    unread: "Unread",
    emptyTitle: "Nothing new for now.",
    emptyBody: "When OpenNexo publishes updates, news, or important notices, they will show up here.",
    allRead: "You're up to date",
    allReadBody: "You have already opened every announcement.",
    markAll: "Mark all as read",
    open: "View announcement",
    new: "New",
    featured: "Featured",
    pinned: "Pinned",
    back: "Back to announcements",
    acknowledge: "Got it",
    acknowledged: "Acknowledgement recorded",
    loadError: "Could not load announcements.",
    previous: "Previous",
    next: "Next",
    byline: "OpenNexo",
    bellTitle: "New OpenNexo update",
    bellOpen: "Open announcements",
    adminNew: "New announcement",
    adminSearch: "Search...",
    draft: "Draft",
    scheduled: "Scheduled",
    published: "Published",
    archived: "Archived",
    saveDraft: "Save draft",
    preview: "Preview",
    publish: "Publish now",
    schedule: "Schedule",
    content: "Content",
    summary: "Summary",
    category: "Category",
    cover: "Cover",
    coverHint: "Optional. PNG, JPEG, WebP, or GIF up to 2 MB.",
    body: "Body",
    audience: "Audience",
    allOrgs: "All organizations",
    specificOrgs: "Specific organizations",
    specificPlans: "Specific plans",
    searchOrgs: "Search organization",
    priority: "Priority",
    normal: "Normal",
    important: "Important",
    critical: "Critical",
    notify: "Send to the notification center",
    feature: "Feature",
    pin: "Pin to top",
    requireAck: "Require read acknowledgement",
    when: "When to publish?",
    now: "Now",
    later: "Schedule",
    date: "Date and time",
    timezone: "Timezone",
    visibleUntil: "Visible until",
    ctaText: "Button label",
    ctaUrl: "Destination",
    cancel: "Cancel",
    publishConfirm: "Publish announcement?",
    publishHint: "This announcement will be available to",
    users: "users",
    organizations: "organizations",
    confirm: "Publish",
    archive: "Archive",
    duplicate: "Duplicate",
    remove: "Delete",
    removeConfirm: "Remove this announcement from the board? The record stays in the admin history.",
    renotify: "Notify again",
    renotifyConfirm: "This marks the announcement unread for eligible users and sends the notice again. Continue?",
    metrics: "Metrics",
    reachedOrgs: "Organizations reached",
    eligibleUsers: "Eligible users",
    reads: "Users who read",
    readRate: "Read rate",
    acks: "Acknowledgements",
    metricsHint: "A read is counted when someone opens the announcement. Card impressions are not tracked.",
    status: "Status",
    audienceCol: "Audience",
    unsaved: "You have unsaved changes. Leave anyway?",
    desktop: "Desktop",
    mobile: "Mobile",
    previewTitle: "Preview",
    noPlans: "No active plans found.",
    saved: "Draft saved.",
    publishedOk: "Announcement is live.",
    scheduledOk: "Announcement scheduled.",
    categoryName: "Category name",
    addCategory: "New category",
  },
} as const;

export type AnnouncementCopy = { [K in keyof (typeof announcementCopy)["pt-BR"]]: string };

export function announcementText(locale: string): AnnouncementCopy {
  return locale === "en" ? announcementCopy.en : announcementCopy["pt-BR"];
}
